Chunk ::= Block
Block ::= Statement*
Empty ::= ';'
Statement ::= Empty | Trycatch | Import | Assignment | Condition | Forloop | Whileloop | Functiondef | Classdef | Return | Processkeys
Trycatch ::= try '{' Statement* '}' except '{' Statement* '}' (finally '{' Statement* '}')?
Import ::= import Name (as Name)?
Assignments ::= Assignment (',' Assignment)*
Assignment ::= (Vars '=')? Expressions
Condition ::= if Expression '{' Block? '}' (elseif Expression '{' Block? '}')* (else '{' Block? '}')?
Foroop ::= for Names in Expressions '{' Block? '}'
Whileloop ::= while Expression '{' Block? '}'
Return ::= return Expressions?
Processkeys ::= continue | break | yield | pass

Expressions ::= Expression (',' Expression)*
Expression ::= Var | Functioncall | Classgen | '(' Expression ')' | Literaltypes
Vars ::= Var (',' Var)*
Var ::= Name | Expression | Expression '[' (Expression | Slice) ']' | Expression '.' Name
Slice ::= Expression? ':' Expression? ':' Expression?
Names ::= Name (',' Name)*
Literaltypes ::= nil | Bool | String | Bytes | Number | Tuple | List | Dict

Functioncall ::= Var '(' Expressions? (',' '*' Expression)? (',' '**' Expression)? ')'
Functiondef ::= func (name '::')? Name '(' Params? ')' '{' Block? '}'
Args ::= '(' Expressions? ')'
Params ::= Names (',' '*' Name)? (',' '**' Name)?
Name ::= (_A-Za-z)(_0-9A-Za-z)*

Classgen ::= Var Args
Classdef ::= class Name '{' (Name ('=' Expression)?)* '}'

Bool ::= true | false
String ::= 's'? '"' [^"]* '"' | 's'? "'" [^']* "'"
Bytes ::= 'b' '"' [^"]* '"' | 'b' "'" [^']* "'"
Number ::= [xX] [0-9a-fA-F]* (.[0-9a-fA-F]*)? ([pP][+\-]? [0-9+])? | [0-9]* (.[0-9]*)? ([eE][+\-]? [0-9]+)?
Tuple ::= Expression ',' | '(' Expression ',' ')' | Expression (',' Expression)+ | '(' Expression (',' Expression)+ ')'
List ::= '[' Expressions? ']'
Dict ::= '{' Expression ':' Expression (',' Expression ':' Expression)* '}'
